library file_type;

Map _mimeMaps = const {
  '3ds': 'image/x-3ds',
  '3g2': 'video/3gpp2',
  '3gp': 'video/3gpp',
  'asx': 'video/x-ms-asf',
  'avi': 'video/x-msvideo',
  'avs': 'video/avs',
  'avx': 'video/x-rad-screenplay',
  'axv': 'video/annodex',
  'bmp': 'image/bmp',
  'cgm': 'image/cgm',
  'dib': 'image/bmp',
  'djv': 'image/vnd.djvu',
  'djvu': 'image/vnd.djvu',
  'dv': 'video/x-dv',
  'dvb': 'video/vnd.dvb.file',
  'dwf': 'model/vnd.dwf',
  'dwg': 'image/vnd.dwg',
  'dxf': 'image/vnd.dxf',
  'flc': 'video/flc',
  'fli': 'video/x-fli',
  'flv': 'video/x-flv',
  'fpx': 'image/vnd.fpx',
  'fst': 'image/vnd.fst',
  'fvi': 'video/isivideo',
  'fvt': 'video/vnd.fvt',
  'g3': 'image/g3fax',
  'gif': 'image/gif',
  'h261': 'video/h261',
  'h263': 'video/h263',
  'h264': 'video/h264',
  'heic': 'image/heic',
  'heif': 'image/heif',
  'hevc': 'video/mp4',
  'ico': 'image/x-icon',
  'ief': 'image/ief',
  'jp2': 'image/jp2',
  'jpe': 'image/jpeg',
  'jpeg': 'image/jpeg',
  'jpg': 'image/jpeg',
  'jpgm': 'video/jpm',
  'jpgv': 'video/jpeg',
  'jpm': 'video/jpm',
  'm1v': 'video/mpeg',
  'm4u': 'video/vnd.mpegurl',
  'm4v': 'video/x-m4v',
  'mdi': 'image/vnd.ms-modi',
  'mj2': 'video/mj2',
  'mjp2': 'video/mj2',
  'mk3d': 'video/x-matroska',
  'mks': 'video/x-matroska',
  'mkv': 'video/x-matroska',
  'mng': 'video/x-mng',
  'mov': 'video/quicktime',
  'movie': 'video/x-sgi-movie',
  'mp4': 'video/mp4',
  'mp4v': 'video/mp4',
  'mpe': 'video/mpeg',
  'mpeg': 'video/mpeg',
  'mpg': 'video/mpeg',
  'mpg4': 'video/mp4',
  'mpv2': 'video/mpeg2',
  'mqv': 'video/quicktime',
  'mxu': 'video/vnd.mpegurl',
  'npx': 'image/vnd.net-fpx',
  'ogv': 'video/ogg',
  'pbm': 'image/x-portable-bitmap',
  'pcd': 'image/x-photo-cd',
  'pct': 'image/x-pict',
  'pcx': 'image/x-pcx',
  'pgm': 'image/x-portable-graymap',
  'pic': 'image/x-pict',
  'pict': 'image/pict',
  'png': 'image/png',
  'pnm': 'image/x-portable-anymap',
  'pnt': 'image/x-macpaint',
  'qt': 'video/quicktime',
  'qti': 'image/x-quicktime',
  'qtif': 'image/x-quicktime',
  'sgi': 'image/sgi',
  'sid': 'image/x-mrsid-image',
  'smv': 'video/x-smv',
  'svg': 'image/svg+xml',
  'svgz': 'image/svg+xml',
  'targa': 'image/x-targa',
  'tif': 'image/tiff',
  'tiff': 'image/tiff',
  'uvg': 'image/vnd.dece.graphic',
  'uvh': 'video/vnd.dece.hd',
  'uvi': 'image/vnd.dece.graphic',
  'uvm': 'video/vnd.dece.mobile',
  'uvp': 'video/vnd.dece.pd',
  'uvs': 'video/vnd.dece.sd',
  'uvu': 'video/vnd.uvvu.mp4',
  'uvv': 'video/vnd.dece.video',
  'uvvg': 'image/vnd.dece.graphic',
  'uvvh': 'video/vnd.dece.hd',
  'uvvi': 'image/vnd.dece.graphic',
  'uvvm': 'video/vnd.dece.mobile',
  'uvvp': 'video/vnd.dece.pd',
  'uvvs': 'video/vnd.dece.sd',
  'uvvu': 'video/vnd.uvvu.mp4',
  'uvvv': 'video/vnd.dece.video',
  'wbmp': 'image/vnd.wap.wbmp',
  'wdp': 'image/vnd.ms-photo',
  'webm': 'video/webm',
  'webp': 'image/webp',
  'wm': 'video/x-ms-wm',
  'wmv': 'video/x-ms-wmv',
  'wmx': 'video/x-ms-wmx',
  'xbm': 'image/x-xbitmap',
  'xif': 'image/vnd.xiff',
  'xpm': 'image/x-xpixmap',
  'xwd': 'image/x-xwindowdump',
};

fileStringType(String file) {
  int index = file.lastIndexOf(".") + 1;
  String type = _mimeMaps[file.toLowerCase().substring(index)];
  return type.split('/').first;
}

urlreturnId(String url) {
  int index = url.lastIndexOf(".") + 1;
  String type = _mimeMaps[url.toLowerCase().substring(index)];
  if (type.split('/').first == "image") {
    return 1;
  } else {
    return 2;
  }
}

